from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yml"


# declare https://github.com/ZandvakiliLab/fastq-prep-and-align as a module
module fastq_prep_and_align:
    snakefile: 
        github("ZandvakiliLab/fastq-prep-and-align", path="workflow/Snakefile", branch="main")
    config:
        config


# use all rules from https://github.com/ZandvakiliLab/fastq-prep-and-align
use rule * from fastq_prep_and_align
